### ISSUE TITLE
ExponentialMovingAverage not found in checkpoint

### ISSUE THREAD

**Issue by TInaZhouzzzzz** [wenwei202/terngrad#6]
when eval
bazel-bin/inception/imagenet_eval \
--data_dir ~/dataset/imagenet-data/ \
--net alexnet \
--image_size 224 \
--batch_size 50 \
--checkpoint_dir /tmp/imagenet_train  \
--restore_avg_var True \
--eval_dir /tmp/imagenet_eval

error : ExponentialMovingAverage not found in checkpoint

**Comment by wenwei202** [comment]
Try to add `--tower 0`

Node that, in TernGrad, parameters are allocated in each GPU to reduce communication because we can communicate quantized gradients instead of floating parameters. By default, the program saves parameters in all GPUs. To evaluate/test, use --tower <gpu_id> to specify which GPU's parameters you want to test on. (We will try to remove this feature to save storage, because the parameter sets are identical across all GPUs). Alteratively, you can use --save_tower 0 in training executables to avoid saving duplicated parameters, in which case, --tower <gpu_id> is unnecessary during evaluation/testing.

**Comment by TInaZhouzzzzz** [comment]
Thank you for your help. I solved my problem.
And I have an other question.I don't know how many epochs I have trained. which script should I see to 
 know ?  I try to `vi inception/inception_train.py ` and there seems no answer

**Comment by wenwei202** [comment]
Somehow, the flag is moved to `https://github.com/wenwei202/terngrad/blob/master/terngrad/inception/bingrad_common.py#L23`

Use `bazel-bin/inception/inception_train --help` for all usages.
